MyAppointment/MyAppointment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyAppointmentBookingSystem.urls')),
    path('', include('account.urls')),
]

MyAppointment/MyAppointmentBookingSystem/urls.py
from django.urls import path
from . import views

app_name = 'MyAppointmentBookingSystem'
urlpatterns = [
    path('', views.index, name='index'),
]

MyAppointment/account/urls.py
from django.urls import path
from . import views

app_name = "account"   

urlpatterns = [
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
]

MyAppointment/MyAppointmentBookingSystem/models.py
from django.db import models

# Create your models here.

MyAppointment/account/models.py
from django.db import models

# Create your models here.

MyAppointment/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

MyAppointment/MyAppointmentBookingSystem/views.py
from typing import ContextManager
from django.shortcuts import render
from .models import *

# Create your views here.
def index(request):
    page_title = "MyAppointment - Home"
    context = {
        "page_title": page_title,
    }
    return render(request, 'MyAppointmentBookingSystem/index.html', context)

MyAppointment/account/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("MyAppointmentBookingSystem:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm
    page_title = "MyAppointment - Register"
    context={
        "register_form":form,
        "page_title":page_title
        }
    return render(request, "account/register.html", context)

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None: #after verified correct user, login user
                login(request,user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("MyAppointmentBookingSystem:index")
            else:
                messages.error(request, "Invalid username or password.")
        else: # form is not valid
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    page_title = "MyAppointment - Login"
    context = {
        "login_form":form,
        "page_title":page_title
        }
    return render(request, "account/login.html", context)

def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("MyAppointmentBookingSystem:index")

MyAppointment/MyAppointmentBookingSystem/templates/MyAppointmentBookingSystem/index.html
{% extends 'base.html' %}
{% load static %}

{% block styles_css %}
    <link rel="stylesheet" href="{% static 'MyAppointmentBookingSystem/css/index.css' %}">
{% endblock %}

{% block page_content %}
{% include "messages.html" %}
<div class="main">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'MyAppointmentBookingSystem/img/clinic.jpg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'MyAppointmentBookingSystem/img/covid-reminder.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'MyAppointmentBookingSystem/img/ambulance.jpg' %}" alt="Third slide">
        </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>
    <div>
      {% if user.is_authenticated %}
          <h4>Dear, {{user.username}}</h4>
      {% endif %}
      <h2 style="text-align: center;">Welcome to our health appointment booking system 👋 - MyAppointment.</h2>
    </div>

  <div class="container">
    <div class="row">
      <!-- 1st Card -->
        <div class="col-sm-4 py-5">
          <div class="card">
            <a href="#">
              <img src="{% static 'MyAppointmentBookingSystem/img/youngpeople.jpg'%}" class="card-img-top" alt="Personal-Health">
            </a>
              <div class="card-body h-100">
              <h5 class="card-title">Personal Health</h5>
              <p class="card-text">Manage your appointment here.</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><a href="">Book Appointment</a></li>
              <li class="list-group-item"><a href="">Reschedule Appointment</a></li>
              <li class="list-group-item"><a href="">Cancel Appointment</a></li>
            </ul>
            <div class="card-body">
              <a href="#" class="card-link">Access all services</a>
            </div>
          </div>
        </div>  
        <!-- 2nd Card -->
        <div class="col-sm-4 py-5">
          <div class="card">
            <a href="#">
              <img src="{% static 'MyAppointmentBookingSystem/img/clinic-1.jpg'%}" class="card-img-top" alt="Directories">
            </a>
            <div class="card-body h-100">
              <h5 class="card-title">Directories</h5>
              <p class="card-text">Find your way around clinics here.</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><a href="">Nearby Clinic & Hospital</a></li>
              <li class="list-group-item"><a href="">Search Specialist Clininc</a></li>
              <li class="list-group-item"><a href="">Covid-19 Vaccination Centre</a></li>
            </ul>      
          </div>
        </div>
        <!-- 3rd Card -->
        <div class="col-sm-4 py-5">
          <div class="card">
            <a href="#">
              <img src="{% static 'MyAppointmentBookingSystem/img/52920.jpg'%}" class="card-img-top" alt="Health-Articles">
            </a>
            <div class="card-body h-100">
              <h5 class="card-title">Live Healthy</h5>
              <p class="card-text">Health Articles</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><a href="">Medical Costs & Financing</a></li>
              <li class="list-group-item"><a href="">Health Articles & Programmes</a></li>
            </ul>          
          </div>
        </div> 
    </div>
  </div>
</div>
{% endblock %}

MyAppointment/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<!-- Bootstrap icons -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<!--Jquery, popper.js, bootstrap-->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

		<!-- DataTables CDN -->
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
		<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>

		<!-- Custom base CSS -->
		<link rel="stylesheet" href="{% static "MyAppointmentBookingSystem/css/style.css" %}">
		{% block styles_css %}{% endblock %}
		<title>{{ page_title }}</title>
	</head>
	<body>
		{% include "nav.html" %}

		<div class="content-wrapper">
			{% block page_content %}{% endblock %}
		</div>

		{% include "footer.html" %}

		<!-- Custom JS -->
		<script type="text/javascript" src="{% static "MyAppointmentBookingSystem/script/scripts.js" %}"></script>
	</body>
</html>

MyAppointment/templates/footer.html
<footer class="fixed-bottom font-small special-color-dark bg-dark text-white pt-3">
	<!-- Social buttons -->
	<ul class="list-unstyled list-inline text-center text-decoration-none">
		<li class="list-inline-item">
			<a href="https://www.facebook.com/" class="fa fa-facebook mx-1 fa-lg" target="_blank"></a> 
		</li>
		<li class="list-inline-item">
			<a href="https://twitter.com/?lang=en" class="fa fa-twitter mx-1 fa-lg" target="_blank"></a>
		</li>
		<li class="list-inline-item">
			<a href="https://www.linkedin.com/" class="fa fa-linkedin-square mx-1 fa-lg" target="_blank"></a>
		</li>
		<li class="list-inline-item">
			<a href="https://www.google.com/" class="fa fa-google mx-1 fa-lg" target="_blank"></a>
		</li>
	</ul>
	<div class="text-center py-3 font-weight-bold">Copyright © 2021:
		<span>MyAppointment</span>
	</div>
</footer>

MyAppointment/templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

MyAppointment/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand bg-dark text-white font-weight-bold" href="{% url 'MyAppointmentBookingSystem:index' %}">Home</a>
		</div>
		
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		{% if user.is_authenticated %}
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link bg-dark text-white font-weight-bold" href="">Patient Record Management</a>
				</li>
				<li class="nav-item">
					<a class="nav-link bg-dark text-white font-weight-bold" href="">Manage Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link btn btn-danger text-white font-weight-bold" href="{% url 'account:logout' %}">Logout</a>
				</li>

				{% else %}

				<li class="nav-item">
					<a class="btn btn-primary text-white font-weight-bold" href="{% url 'account:login' %}">Login</a></button>
					<a class="btn btn-primary text-white font-weight-bold" href="{% url 'account:register' %}">Register</a></button>
				</li>
			</ul>
		</div>
		{% endif %}
	</div>
</nav>